FROM postgres:latest

ENV POSTGRES_DB=hospital_appointment_scheduler
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# COPY init.sql /docker-entrypoint-initdb.d/
# COPY init.sh /docker-entrypoint-initdb.d/

EXPOSE 5432