export const ERROR_MESSAGE = {
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXISTS: "User already exists",
  INVALID_CREDENTIALS: "Invalid credentials",
  INVALID_TOKEN: "Invalid token",
  INVALID_PASSWORD_OR_EMAIL: "Invalid password or email",
  SERVER_ERROR: "Internal server error",
  SPECIALTY_NOT_FOUND: "Specialty not found",
  FORBIDDEN: "Forbidden",
  UNAUTHORIZED: "Unauthorized",
  DAY_OF_WEEK_NOT_FOUND: "Day of week not found",
  AVAILABILITY_NOT_FOUND: "Availability not found",
  AVAILABILITY_EXPIRED: "Availability expired",
  AVAILABILITY_ALREADY_EXISTS: "Availability already exists",
};
